-- CREATE ROLE PROFESSOR PASSWORD
CREATE ROLE PROFESSOR;

GRANT SELECT ON HOSPEDE TO PROFESSOR;

CREATE USER TIAGO PASSWORD '123' IN ROLE PROFESSOR;



-- EXERCICIO
CREATE OR REPLACE VIEW DADOS_HOSPEDES 
AS 
SELECT NOME, DT_NASC FROM HOSPEDE;

CREATE OR REPLACE FUNCTION HOSPEDAR(COD_HOSP )