-- OBTER O NOME DOS HOSPEDES QUE SE HOSPEDARAM NO APTO 202:
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN 
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM = 202);

SELECT NOME FROM HOSPEDE H, HOSPEDAGEM HO 
WHERE H.COD_HOSP = HO.COD_HOSP AND NUM = 202;

SELECT NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP WHERE NUM = 202;


-- OBTER O NOME DOS HOSPEDES QUE NUNCA SE HOSPEDARAM (SEM USAR "NOT IN" E "EXCEPT"):
-- NOT IN
SELECT NOME FROM HOSPEDE WHERE COD_HOSP NOT IN (SELECT COD_HOSP FROM HOSPEDAGEM);

-- EXCEPT
SELECT NOME FROM (
SELECT COD_HOSP, NOME FROM HOSPEDE 
EXCEPT 
SELECT H.COD_HOSP, NOME FROM HOSPEDE H, HOSPEDAGEM HO
WHERE H.COD_HOSP = HO.COD_HOSP);

-- OUTER JOIN
SELECT NOME FROM HOSPEDE H LEFT JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP WHERE COD_HOSPEDA IS NULL;


-- O NOME DE TODAS AS CATEGORIAS E, QUANDO POSSÍVEL, OS NÚMEROS DO RESPECTIVO APARTAMENTO
SELECT NOME, NUM FROM APTO A RIGHT OUTER JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT;

SELECT NOME, NUM FROM APTO A RIGHT JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT;

SELECT NOME, NUM FROM APTO A LEFT JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT;

SELECT NOME, NUM FROM APTO A FULL JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT;


-- ORDER BY
SELECT * FROM HOSPEDE ORDER BY NOME ASC;

SELECT * FROM HOSPEDE ORDER BY NOME DESC;

SELECT * FROM HOSPEDE ORDER BY NOME, DT_NASC;

SELECT * FROM HOSPEDE ORDER BY NOME DESC, DT_NASC ASC;

SELECT COD_HOSP FROM HOSPEDE ORDER BY NOME DESC, DT_NASC ASC;


-- GROUP BY (PARA CADA...)
SELECT NOME, COUNT(NOME) QUANTIDADE FROM HOSPEDE GROUP BY NOME 
ORDER BY QUANTIDADE DESC;

SELECT NOME, COUNT(NOME) QUANTIDADE FROM HOSPEDE GROUP BY NOME 
ORDER BY 2 DESC;

-- DISTINCT
SELECT DISTINCT NOME FROM HOSPEDE;


-- OBTER A QUANTIDADE DE HOSPEDAGENS REALIZADAS POR CADA NOME DE HÓSPEDE
SELECT NOME, COUNT(H.COD_HOSP) QUANTIDADE FROM HOSPEDE H JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP GROUP BY NOME;

SELECT NOME, COUNT(*) QUANTIDADE FROM HOSPEDE H JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP GROUP BY NOME;


-- OBTER, PARA CADA NOME DE CATEGORIA, A QUANTIDADE DE HOSPEDAGENS REALIZADAS
SELECT NOME, COUNT(*) QUANTIDADE FROM CATEGORIA C JOIN APTO A ON C.COD_CAT = A.COD_CAT 
JOIN HOSPEDAGEM HO ON A.NUM = HO.NUM GROUP BY NOME;


-- QUESTÃO 4 (SEM USAR "SELECT" NA CLAÚSURA "FROM")
-- SELECT NA CLAÚSURA FROM
SELECT NOME FROM (
SELECT NOME, COUNT(NOME) QUANTIDADE FROM APTO A JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT GROUP BY NOME)
WHERE QUANTIDADE = 1;

SELECT NOME FROM APTO A JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT GROUP BY NOME HAVING COUNT(NOME) = 1;