CREATE OR REPLACE FUNCTION FUNCAO_CONTROLA_ITEM()
RETURNS TRIGGER
AS
$$
BEGIN

IF TG_OP = 'INSERT' THEN
UPDATE LIVRO SET QTD_ESTOQUE = QTD_ESTOQUE - NEW.QUANT WHERE COD_LIVRO = NEW.COD_LIVRO;
UPDATE PEDIDO SET QUANT_ITENS = QUANT_ITENS + NEW.QUANT, 
VALOR_TOTAL_PEDIDO = VALOR_TOTAL_PEDIDO + (NEW.VALOR_TOTAL_ITEM)
WHERE COD_PEDIDO = NEW.COD_PEDIDO;
ELSIF TG_OP = 'DELETE' THEN

ELSIF TG_OP = 'INSERT' THEN 

END IF;
RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;


CREATE TRIGGER CONTROLA_ITEM
BEFORE INSERT OR DELETE OR UPDATE
ON ITEM_PEDIDO
FOR EACH ROW
EXECUTE PROCEDURE FUNCAO_CONTROLA_ITEM;