SELECT * FROM HOSPEDE;


CREATE OR REPLACE VIEW HOSPEDE_J
AS 
SELECT * FROM HOSPEDE WHERE NOME ILIKE 'J%';


SELECT * FROM HOSPEDE_J;


INSERT INTO HOSPEDE VALUES (7, 'JOANINHA', NULL);

INSERT INTO HOSPEDE_J VALUES (8, 'JOANA', NULL);

INSERT INTO HOSPEDE_J VALUES (9, 'MARIAZINHA', NULL);


CREATE OR REPLACE VIEW HOSPEDE_J
AS 
SELECT * FROM HOSPEDE WHERE NOME ILIKE 'J%'
WITH CHECK OPTION;


INSERT INTO HOSPEDE_J VALUES (10, 'GUSTAVO', NULL);


CREATE OR REPLACE VIEW HOSPEDE_J2
AS 
SELECT NOME, DT_NASC FROM HOSPEDE WHERE NOME ILIKE 'J%'
WITH CHECK OPTION;


INSERT INTO HOSPEDE_J2 VALUES ('JULIA', NULL);


CREATE MATERIALIZED VIEW HOSPEDE_J3
AS 
SELECT * FROM HOSPEDE WHERE NOME ILIKE 'J%';


REFRESH MATERIALIZED VIEW HOSPEDE_J3;


SELECT * FROM HOSPEDE_J3;


INSERT INTO HOSPEDE VALUES (10, 'JEFERSSON', NULL);


CREATE MATERIALIZED VIEW HOSPEDE_J4
AS 
SELECT * FROM HOSPEDE WHERE NOME ILIKE 'J%'
WITH NO DATA;

REFRESH MATERIALIZED VIEW HOSPEDE_J4;

SELECT * FROM HOSPEDE_J4;


CREATE MATERIALIZED VIEW HOSPEDE_J_J
AS 
SELECT COD_HOSP, NOME FROM HOSPEDE_J;

SELECT * FROM HOSPEDE_J_J;

DROP VIEW HOSPEDE_J;


CREATE TABLE VENDA (
COD_VENDA SERIAL NOT NULL PRIMARY KEY,
NOME_VENDEDOR VARCHAR(40) NOT NULL, 
DATA_VENDA DATE NOT NULL,
VALOR_VENDIDO FLOAT NOT NULL
);

-- 1
INSERT INTO VENDA VALUES 
(DEFAULT, 'JOÃO', '2024-03-01', 500),
(DEFAULT, 'MARIA', '2024-03-02', 500),
(DEFAULT, 'JOSÉ', '2024-03-03', 100),
(DEFAULT, 'JOANA', '2024-03-04', 150),
(DEFAULT, 'JOÃO', '2024-04-01', 50),
(DEFAULT, 'MARIA', '2024-04-02', 100),
(DEFAULT, 'JOSÉ', '2024-04-03', 200),
(DEFAULT, 'JOANA', '2024-04-04', 300),
(DEFAULT, 'JOÃO', '2024-05-01', 200),
(DEFAULT, 'MARIA', '2024-05-02', 100);

-- 2.1
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO FROM VENDA 
-- WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31' 
WHERE EXTRACT (YEAR FROM DATA_VENDA) = 2024 AND 
EXTRACT (MONTH FROM DATA_VENDA) = 3
GROUP BY NOME_VENDEDOR HAVING SUM(VALOR_VENDIDO) > 400
ORDER BY TOTAL_VENDIDO DESC;

-- 2.2
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO FROM VENDA 
WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31' 
GROUP BY NOME_VENDEDOR
ORDER BY TOTAL_VENDIDO DESC LIMIT 1;

-- 3
CREATE VIEW TOTAL_DE_VENDAS_MARCO AS
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) TOTAL_VENDIDO FROM VENDA 
WHERE DATA_VENDA BETWEEN '2024-03-01' AND '2024-03-31' 
GROUP BY NOME_VENDEDOR
ORDER BY TOTAL_VENDIDO DESC;

SELECT NOME_VENDEDOR, TOTAL_VENDIDO FROM TOTAL_DE_VENDAS
WHERE TOTAL_VENDIDO = (SELECT MAX(TOTAL_VENDIDO) FROM TOTAL_DE_VENDAS_MARCO);