CREATE INDEX nome ON tabela USING tipo(campo);

CREATE TABLE PESSOA(
	COD SERIAL,
	IDADE INT
);

CREATE OR REPLACE FUNCTION INSERE_PESSOA()
RETURNS VOID
AS $$
DECLARE
	CONT INT=1;
BEGIN
	WHILE (CONT<=500000) LOOP
		INSERT INTO PESSOA VALUES (DEFAULT, RANDOM()*100);
		CONT:=CONT+1;
	END LOOP;
END;
$$ LANGUAGE PLPGSQL;

INSERE_PESSOA();

EXPLAIN ANALYSE SELECT * FROM PESSOA WHERE IDADE=22;

CREATE INDEX TESTA ON PESSOA USING BTREE(IDADE);