-- QUESTÃO 01
SELECT J.COD_JOGADOR, J.NOME, COALESCE(CAST(MIN(DT_FUNDACAO) AS TEXT), 'NÃO POSSUI TIME')
FROM JOGADOR J LEFT JOIN JOGATIME JT
ON J.COD_JOGADOR = JT.COD_JOGADOR LEFT JOIN TIME T
ON JT.COD_TIME = T.COD_TIME
GROUP BY J.COD_JOGADOR, J.NOME;

-- QUESTÃO 02
SELECT NOME_TIME FROM (SELECT NOME_TIME, COUNT(COD_TIME_MANDANTE) MANDANTE
FROM TIME T LEFT JOIN JOGO J
ON T.COD_TIME = J.COD_TIME_MANDANTE
GROUP BY NOME_TIME)
WHERE MANDANTE = 0
INTERSECT
SELECT NOME_TIME FROM (SELECT NOME_TIME, COUNT(COD_TIME_VISITANTE) VISITANTE
FROM TIME T LEFT JOIN JOGO J
ON T.COD_TIME = J.COD_TIME_VISITANTE
GROUP BY NOME_TIME)
WHERE VISITANTE = 0

-- QUESTÃO 04
CREATE OR REPLACE FUNCTION VERIFICAR_CONFRONTO()
RETURNS TRIGGER
AS $$
BEGIN
	IF NEW.COD_TIME_MANDANTE = (SELECT COD_TIME_MANDANTE FROM JOGO 
	WHERE COD_TIME_MANDANTE = NEW.COD_TIME_MANDANTE AND COD_TIME_VISITANTE = NEW.COD_TIME_VISITANTE) THEN
		RAISE EXCEPTION 'CONFRONTO INVÁLIDO! O TIME MANDANTE JÁ TEVE 1 MANDO DE CAMPO NESSE CONFRONTO';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER VERIFICACAO_CONFRONTO
BEFORE INSERT
ON JOGO
FOR EACH ROW
EXECUTE PROCEDURE VERIFICAR_CONFRONTO();
