-- 7
SELECT NOME FROM CATEGORIA WHERE LENGTH(NOME) > 15;


-- 10
ALTER TABLE FUNCIONARIO ADD COLUMN SALARIO FLOAT NOT NULL DEFAULT 0;


-- 11
SELECT NOME, SALARIO + COUNT(COD_HOSPEDA) * 10;
FROM FUNCIONARIO F LEFT JOIN HOSPEDAGEM HO 
ON F.COD_FUNC = HO.COD_FUNC 
GROUP BY NOME, SALARIO;


-- 13
SELECT NOME, COALESCE(CAST(NUM AS TEXT), 'NÃO POSSUI APTO') 
FROM CATEGORIA C JOIN APTO A 
ON C.COD_CAT = A.COD_CAT;


-- 15
SELECT COD_HOSPEDA FROM HOSPEDAGEM WHERE 
COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDE WHERE 
DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE WHERE 
COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDAGEM WHERE
NUM IN (SELECT NUM FROM APTO WHERE 
COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE 
VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA))))));


-- 16
-- COM SUBQUERY
SELECT NOME FROM HOSPEDE WHERE DT_NASC 
IN (SELECT DT_NASC FROM HOSPEDE WHERE COD_HOSP = 2) AND COD_HOSP != 2;

-- SEM SUBQUERY
SELECT H2.NOME FROM HOSPEDE H1, HOSPEDE H2 
WHERE H1.COD_HOSP != H2.COD_HOSP AND H1.DT_NASC = H2.DT_NASC;


-- 21
SELECT H.NOME, DT_ENT, DT_SAI, (DT_SAI - DT_ENT) * VALOR_DIA VALOR_TOTAL_PAGO
FROM HOSPEDE H JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT;
