-- 1
SELECT NOME, DT_NASC FROM HOSPEDE ORDER BY NOME ASC, DT_NASC DESC;

-- 2
SELECT NOME CATEGORIAS FROM CATEGORIA ORDER BY CATEGORIA ASC;

-- 3
SELECT VALOR_DIA, NUM FROM CATEGORIA C JOIN APTO A
ON C.COD_CAT = A.COD_CAT ORDER BY VALOR_DIA DESC;

-- 4
SELECT NOME FROM (SELECT NOME, COUNT(NUM) QUANTIDADE FROM CATEGORIA C JOIN APTO A
ON C.COD_CAT = A.COD_CAT GROUP BY NOME) WHERE QUANTIDADE = 1;

-- 5
SELECT NOME, EXTRACT(MONTH FROM DT_NASC) MES, EXTRACT(YEAR FROM DT_NASC) ANO 
FROM HOSPEDE WHERE NACIONALIDADE = 'NÃO INFORMADA' 
ORDER BY DT_NASC ASC, NOME ASC;

-- 6
SELECT NOME, NUM, QUANTIDADE FROM (SELECT NOME, NUM, COUNT(H.COD_HOSP) QUANTIDADE 
FROM HOSPEDE H JOIN HOSPEDAGEM HO ON H.COD_HOSP = HO.COD_HOSP
GROUP BY NOME, NUM) ORDER BY QUANTIDADE DESC;

-- 7
SELECT NOME FROM CATEGORIA WHERE LENGTH(NOME) > 15;

-- 8
SELECT A.NUM, NOME FROM HOSPEDAGEM H JOIN APTO A 
ON H.NUM = A.NUM JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT WHERE (DT_ENT BETWEEN '01-01-2017' AND'31-12-2017') 
OR (DT_SAI BETWEEN '01-01-2017' AND '31-12-2017');

-- 11
SELECT NOME, (SALARIO + QUANTIDADE * 10) FROM (SELECT NOME, SALARIO, COUNT(F.COD_FUNC) QUANTIDADE 
FROM FUNCIONARIO F LEFT JOIN HOSPEDAGEM H
ON F.COD_FUNC = H.COD_FUNC GROUP BY NOME, SALARIO);

-- 12
SELECT NOME, NUM FROM CATEGORIA C LEFT JOIN APTO A
ON C.COD_CAT = A.COD_CAT ORDER BY NOME, NUM;

-- 13
SELECT NOME, COALESCE(CAST(NUM AS TEXT), 'NÃO POSSUI APTO') 
FROM CATEGORIA C LEFT JOIN APTO A 
ON C.COD_CAT = A.COD_CAT ORDER BY NOME, NUM;

-- 14
SELECT F.NOME FROM FUNCIONARIO F JOIN HOSPEDAGEM HO
ON F.COD_FUNC = HO.COD_FUNC JOIN HOSPEDE H
ON HO.COD_HOSP = H.COD_HOSP JOIN RESERVA R
ON F.COD_FUNC = R.COD_FUNC WHERE H.NOME = 'JOÃO' 
UNION
SELECT F.NOME FROM FUNCIONARIO F JOIN HOSPEDAGEM HO
ON F.COD_FUNC = HO.COD_FUNC JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT JOIN RESERVA R
ON F.COD_FUNC = R.COD_FUNC WHERE C.NOME = 'LUXO';

-- 15
SELECT COD_HOSPEDA FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSPEDA JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT 
WHERE H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) 
AND VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA);

-- 16
SELECT H2.NOME FROM HOSPEDE H1, HOSPEDE H2 
WHERE H1.COD_HOSP != H2.COD_HOSP AND H1.DT_NASC = H2.DT_NASC;

-- 17
SELECT H.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT
WHERE H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) 
AND C.VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA)
AND (HO.DT_ENT BETWEEN '2017-01-31' AND '2017-12-31' 
OR HO.DT_SAI BETWEEN '2017-01-31' AND '2017-12-31');

-- 18
SELECT C.NOME FROM FUNCIONARIO F JOIN HOSPEDAGEM HO 
ON F.COD_FUNC = HO.COD_FUNC JOIN HOSPEDE H 
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A 
ON HO.NUM = A.NUM JOIN CATEGORIA C ON
A.COD_CAT = C.COD_CAT WHERE F.NOME LIKE 'MARIA'
OR (H.NOME LIKE 'JOÃO' AND F.NOME LIKE 'JOAQUIM');

-- 19
SELECT NOME, DT_NASC, DIARIA FROM (SELECT F.NOME, F.DT_NASC, MAX(VALOR_DIA) DIARIA 
FROM FUNCIONARIO F JOIN HOSPEDAGEM HO 
ON F.COD_FUNC = HO.COD_FUNC JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C 
ON A.COD_CAT = C.COD_CAT
GROUP BY F.NOME, F.DT_NASC);

-- 20
SELECT NOME, QUANTIDADE FROM (SELECT NOME, COUNT(NUM) QUANTIDADE 
FROM HOSPEDE H JOIN HOSPEDAGEM HO 
ON H.COD_HOSP = HO.COD_HOSP 
GROUP BY NOME);

-- 21
