-- 1
SELECT NOME FROM CATEGORIA WHERE VALOR_DIA BETWEEN 100 AND 200;

-- 2
SELECT NOME FROM CATEGORIA WHERE NOME LIKE '%Luxo%';

-- 3
SELECT NUM FROM APTO WHERE NUM IN (SELECT NUM FROM HOSPEDAGEM WHERE DT_SAI IS NULL);

-- 4
SELECT NUM FROM APTO WHERE COD_CAT IN (1, 2, 3, 11, 34, 54, 24, 12);

-- 5
SELECT * FROM APTO WHERE COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE NOME LIKE 'Luxo%');

-- 6
SELECT COUNT(*) FROM APTO;

-- 7
SELECT SUM(VALOR_DIA) FROM CATEGORIA;

-- 8
SELECT AVG(VALOR_DIA) FROM CATEGORIA;

-- 9
SELECT MAX(VALOR_DIA) FROM CATEGORIA;

-- 10
SELECT MIN(VALOR_DIA) FROM CATEGORIA;

-- 11
SELECT NOME FROM HOSPEDE WHERE DT_NASC >= '1970-01-01';

-- 12
SELECT COUNT(*) FROM HOSPEDE;

-- 13
ALTER TABLE HOSPEDE ADD COLUMN NACIONALIDADE VARCHAR(30) NOT NULL;

-- 14
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);

-- 15
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MAX(DT_NASC) FROM HOSPEDE);

-- 16
SELECT NOME FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);

-- 17
UPDATE CATEGORIA SET VALOR_DIA = VALOR_DIA + (VALOR_DIA * 0.1);

-- 18
SELECT A.NUM FROM APTO A, CATEGORIA C, HOSPEDAGEM H, HOSPEDE HO 
WHERE A.COD_CAT = C.COD_CAT AND A.NUM = H.NUM AND H.COD_HOSP = HO.COD_HOSP 
AND VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA) AND HO.NOME = 'JOÃO';

-- 19
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM NOT IN (201));

-- 20
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN 
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM IN 
(SELECT NUM FROM APTO WHERE COD_CAT IN 
(SELECT COD_CAT FROM CATEGORIA WHERE NOME NOT IN ('LUXO'))));

-- 21
SELECT H.NOME FROM HOSPEDE H, HOSPEDAGEM HO, FUNCIONARIO F WHERE 
H.COD_HOSP = HO.COD_HOSP AND HO.COD_FUNC = F.COD_FUNC AND
H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) AND
F.DT_NASC IN (SELECT MAX(DT_NASC) FROM FUNCIONARIO);

-- 22
SELECT C.NOME FROM HOSPEDE H, HOSPEDAGEM HO, APTO A, CATEGORIA C WHERE
H.COD_HOSP = HO.COD_HOSP AND HO.NUM = A.NUM AND A.COD_CAT = C.COD_CAT AND
VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA) AND 
H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);