-- ATIVIDADE 1
-- 1
SELECT NOME FROM CATEGORIA WHERE VALOR_DIA BETWEEN 100 AND 200;

-- 2
SELECT NOME FROM CATEGORIA WHERE NOME ILIKE '%LUXO%';

-- 3
SELECT NUM FROM HOSPEDAGEM WHERE DT_SAI IS NULL;

-- 4
SELECT NUM FROM APTO WHERE COD_CAT IN (1, 2, 3, 11, 34, 54, 24, 12);

-- 5
SELECT * FROM APTO A JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE C.NOME ILIKE 'LUXO%';

-- 6
SELECT COUNT(*) FROM APTO;

-- 7
SELECT SUM(VALOR_DIA) FROM CATEGORIA;

-- 8
SELECT AVG(VALOR_DIA) FROM CATEGORIA;

-- 9
SELECT MAX(VALOR_DIA) FROM CATEGORIA;

-- 10
SELECT MIN(VALOR_DIA) FROM CATEGORIA;

-- 11
SELECT NOME FROM HOSPEDE WHERE DT_NASC > '1970-01-01';

-- 12
SELECT COUNT(*) FROM HOSPEDE;

-- 13 (ESTUDAR MAIS)
ALTER TABLE HOSPEDE
ADD COLUMN NACIONALIDADE VARCHAR(30) NOT NULL DEFAULT 'NÃO INFORMADA';

-- 14
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);
SELECT H1.DT_NASC FROM HOSPEDE H1
WHERE H1.DT_NASC = (SELECT MIN(H2.DT_NASC) FROM HOSPEDE H2);

-- 15
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MAX(DT_NASC) FROM HOSPEDE);

-- 16
SELECT NOME FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);

-- 17
UPDATE CATEGORIA
SET VALOR_DIA = VALOR_DIA + (0.1 * VALOR_DIA);

-- 18
SELECT HO.NUM FROM HOSPEDAGEM HO JOIN HOSPEDE H
ON HO.COD_HOSP = H.COD_HOSP JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE H.NOME = 'JOÃO' AND VALOR_DIA = (SELECT MAX(VALOR_DIA) FROM CATEGORIA);

-- 19
SELECT H.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP
WHERE NUM NOT IN (201);

-- 20
SELECT H.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE C.NOME NOT IN ('LUXO');

-- 21
SELECT H.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP JOIN FUNCIONARIO F
ON HO.COD_FUNC = F.COD_FUNC
WHERE F.DT_NASC IN (SELECT MAX(DT_NASC) FROM FUNCIONARIO)
AND H.DT_NASC IN (SELECT MIN(H2.DT_NASC) FROM HOSPEDE H2 JOIN HOSPEDAGEM HO2
ON H2.COD_HOSP = HO2.COD_HOSP
WHERE HO2.COD_FUNC = F.COD_FUNC)
LIMIT 1;

-- 22
SELECT H.NOME FROM CATEGORIA C JOIN APTO A 
ON C.COD_CAT = A.COD_CAT JOIN HOSPEDAGEM HO
ON A.NUM = HO.NUM JOIN HOSPEDE H
ON HO.COD_HOSP = H.COD_HOSP
WHERE H.DT_NASC IN (SELECT MIN(H2.DT_NASC) FROM HOSPEDE H2 JOIN HOSPEDAGEM HO2 ON H2.COD_HOSP = HO2.COD_HOSP)
AND C.VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA C2 JOIN APTO A2
ON C2.COD_CAT = A2.COD_CAT JOIN HOSPEDAGEM HO2
ON A2.NUM = HO2.NUM
WHERE HO2.COD_HOSP = H.COD_HOSP)
LIMIT 1;


-- ATIVIDADE 2
-- 1
SELECT NOME, DT_NASC FROM HOSPEDE ORDER BY NOME ASC, DT_NASC DESC;

-- 2
SELECT NOME AS CATEGORIA FROM CATEGORIA ORDER BY NOME ASC;

-- 3
SELECT C.VALOR_DIA, A.NUM FROM APTO A JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
ORDER BY C.VALOR_DIA DESC;

-- 4
SELECT NOME FROM (SELECT C.NOME, COUNT(A.NUM) QUANT FROM APTO A JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT GROUP BY C.NOME) WHERE QUANT = 1;

-- 5
SELECT NOME, EXTRACT(MONTH FROM DT_NASC) MES, EXTRACT(YEAR FROM DT_NASC) ANO FROM HOSPEDE
WHERE NACIONALIDADE = 'BRASILEIRA' ORDER BY NOME ASC, MES ASC, ANO ASC;

-- 6
SELECT NOME, NUM, COUNT(NUM) QUANT FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP
GROUP BY NOME, NUM ORDER BY QUANT DESC;

-- 7
SELECT NOME FROM CATEGORIA WHERE LENGTH(NOME) > 15;

-- 8
SELECT H.NUM, C.NOME FROM HOSPEDAGEM H JOIN APTO A
ON H.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE (H.DT_ENT BETWEEN '2017-01-01' AND '2017-12-31') OR (H.DT_SAI BETWEEN '2017-01-01' AND '2017-12-31');

-- 9 NULL

-- 10
ALTER TABLE FUNCIONARIO
ADD COLUMN SALARIO FLOAT NOT NULL DEFAULT 1.500;

-- 11
SELECT NOME, SALARIO + (10 * QUANT) FROM (SELECT NOME, SALARIO, COUNT(NUM) QUANT 
FROM FUNCIONARIO F LEFT JOIN HOSPEDAGEM H
ON F.COD_FUNC = H.COD_FUNC
GROUP BY NOME, SALARIO);

-- 12
SELECT NOME, NUM FROM CATEGORIA C LEFT JOIN APTO A
ON C.COD_CAT = A.COD_CAT
ORDER BY NOME ASC, NUM ASC;

-- 13
SELECT NOME, COALESCE(CAST(NUM AS TEXT), 'Não possui apartamento') 
FROM CATEGORIA C LEFT JOIN APTO A 
ON C.COD_CAT = A.COD_CAT;

-- 14
SELECT F.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP JOIN FUNCIONARIO F
ON HO.COD_FUNC = F.COD_FUNC JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE H.NOME = 'JOÃO'
UNION
SELECT F.NOME FROM HOSPEDE H JOIN RESERVA R
ON H.COD_HOSP = R.COD_HOSP JOIN FUNCIONARIO F
ON R.COD_FUNC = F.COD_FUNC JOIN APTO A
ON R.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE H.NOME = 'JOÃO' OR C.NOME = 'LUXO';

-- 15
SELECT HO.COD_HOSPEDA FROM HOSPEDE H JOIN HOSPEDAGEM HO
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A
ON HO.NUM = A.NUM JOIN CATEGORIA C
ON A.COD_CAT = C.COD_CAT
WHERE VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA)
AND H.DT_NASC IN (SELECT MIN(H2.DT_NASC) 
FROM HOSPEDE H2 JOIN HOSPEDAGEM HO2
ON H.COD_HOSP = HO.COD_HOSP JOIN APTO A2
ON HO.NUM = A2.NUM 
WHERE A2.COD_CAT = C.COD_CAT);

SELECT * FROM CATEGORIA;