-- 1
INSERT INTO LEITOR(NOME) VALUES ('Laura Nogueira');

-- 2
INSERT INTO FUNCIONARIO(NOME) VALUES ('Pedro Ramos');

-- 3
INSERT INTO AUTOR(NOME, NACIONALIDADE) VALUES ('Lygia Fagundes Telles', 'Brasil');

-- 4
INSERT INTO TITULO(NOME) VALUES ('Ciranda de Pedra');

-- 5
INSERT INTO EXEMPLAR(STATUS, LOCALIZACAO, COD_CAT, COD_TIT) VALUES (TRUE, 'Estante G1', 2, 11);

-- 6
UPDATE LEITOR
SET NOME = 'Ana Carolina Souza'
WHERE COD_LEITOR = 1;

-- 7
UPDATE EXEMPLAR 
SET LOCALIZACAO = 'Estante B2'
WHERE COD_EXE = 3;

-- 8
UPDATE EXEMPLAR
SET STATUS = TRUE
WHERE COD_EXE = 5;

-- 9
UPDATE CATEGORIA
SET VALOR_MULTA = 3.00
WHERE NOME = 'Suspense';

-- 10
UPDATE TITULO
SET NOME = 'Dom Casmurro (Edição Comentada)'
WHERE COD_TIT = 4;

-- 11
SELECT NOME FROM LEITOR WHERE NOME ILIKE 'G%';

-- 12
SELECT COD_EXE FROM EXEMPLAR WHERE STATUS = TRUE;

-- 13
SELECT NOME FROM FUNCIONARIO WHERE NOME ILIKE '%A%'

-- 14
SELECT NOME FROM AUTOR WHERE NACIONALIDADE != 'Brasil';

-- 15
SELECT * FROM EMPRESTIMO WHERE COD_LEITOR = 5;

-- 16
SELECT MIN(VALOR_MULTA) FROM CATEGORIA;

-- 17
SELECT MAX(VALOR_MULTA) FROM CATEGORIA;

-- 18
SELECT AVG(VALOR_MULTA) FROM CATEGORIA;

-- 19
SELECT COUNT(*) FROM LEITOR;

-- 20
SELECT COUNT(*) FROM EXEMPLAR WHERE STATUS = FALSE;

-- 21
SELECT COUNT(*) FROM EXEMPLAR WHERE COD_CAT = 1;

-- 22
SELECT SUM(VALOR_MULTA) FROM CATEGORIA;

-- 23
SELECT NOME, QUANTIDADE FROM (SELECT NOME, COUNT(*) QUANTIDADE 
FROM LEITOR L JOIN EMPRESTIMO E ON L.COD_LEITOR = E.COD_LEITOR GROUP BY(NOME));

-- 24
SELECT AVG(VALOR_MULTA) FROM CATEGORIA WHERE VALOR_MULTA > 1.5;

-- 25
SELECT COUNT(*) FROM AUTOR WHERE NACIONALIDADE = 'Brasil';

-- 26
SELECT NOME FROM TITULO WHERE COD_TIT BETWEEN 2 AND 5;

-- 27
SELECT NOME FROM LEITOR WHERE NOME ILIKE '%E%'

-- 28
SELECT NOME FROM AUTOR WHERE NACIONALIDADE IN ('Brasil', 'Colômbia', 'Portugal');

-- 29
SELECT * FROM EMPRESTIMO WHERE DT_PREV_DEV BETWEEN '2025-04-10' AND '2025-04-20';

-- 30
SELECT * FROM EXEMPLAR WHERE LOCALIZACAO IN ('Estante A1', 'Estante B1', 'Estante D2')
