CREATE TABLE LEITOR (
COD_LEITOR SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL
);

CREATE TABLE FUNCIONARIO (
COD_FUN SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL
);

CREATE TABLE AUTOR (
COD_AUTOR SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
NACIONALIDADE VARCHAR(40) NOT NULL
);

CREATE TABLE TITULO (
COD_TIT SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL
);

CREATE TABLE AUTORIA (
COD_AUT SERIAL NOT NULL PRIMARY KEY,
COD_TIT INT NOT NULL REFERENCES TITULO(COD_TIT),
COD_AUTOR INT NOT NULL REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE CATEGORIA (
COD_CAT SERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
VALOR_MULTA FLOAT NOT NULL
);

CREATE TABLE EXEMPLAR (
COD_EXE SERIAL NOT NULL PRIMARY KEY,
STATUS BOOLEAN NOT NULL,
LOCALIZACAO VARCHAR(40) NOT NULL,
COD_CAT INT NOT NULL REFERENCES CATEGORIA(COD_CAT),
COD_TIT INT NOT NULL REFERENCES TITULO(COD_TIT)
);

CREATE TABLE EMPRESTIMO (
COD_EMP SERIAL NOT NULL PRIMARY KEY,
DT_EMP DATE NOT NULL, 
DT_PREV_DEV DATE NOT NULL,
DT_PREV DATE NOT NULL,
COD_LEITOR INT NOT NULL REFERENCES LEITOR(COD_LEITOR),
COD_EXE INT NOT NULL REFERENCES EXEMPLAR(COD_EXE),
COD_FUN INT NOT NULL REFERENCES FUNCIONARIO(COD_FUN)
);

CREATE TABLE RESERVA (
COD_RES SERIAL NOT NULL PRIMARY KEY,
STATUS BOOLEAN NOT NULL,
DT_RES DATE NOT NULL,
COD_LEITOR INT NOT NULL REFERENCES LEITOR(COD_LEITOR),
COD_TIT INT NOT NULL REFERENCES TITULO(COD_TIT)
);